info:
  app:
    name: Pizza API
    description: API that allows you to create, read, update and delete data through HTTP endpoints for a pizzeria.
    version: 1.0.0

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      type: trace
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  config:
    import: optional:file:variables.env[.properties]
jwt:
  secret: javainuse

server:
  port: 8090

loggin:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

